// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var checkForWin, clearBoard, isX, resetBoard;
    isX = true;
    clearBoard = function() {
      $('.board-cell').text('');
      return isX = true;
    };
    resetBoard = function() {
      clearBoard();
      $('#gameboard').hide();
      return $('#start-game').fadeIn(500);
    };
    checkForWin = function() {
      var board, win, _ref, _ref1, _ref10, _ref11, _ref12, _ref13, _ref14, _ref15, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _ref9;
      board = ($('.board-cell').map(function(idx, el) {
        return $(el).text();
      })).get();
      win = ((board[0] === (_ref1 = board[1]) && _ref1 === (_ref = board[2])) && _ref !== '') ? board[0] : ((board[3] === (_ref3 = board[4]) && _ref3 === (_ref2 = board[5])) && _ref2 !== '') ? board[3] : ((board[6] === (_ref5 = board[7]) && _ref5 === (_ref4 = board[8])) && _ref4 !== '') ? board[6] : ((board[0] === (_ref7 = board[3]) && _ref7 === (_ref6 = board[6])) && _ref6 !== '') ? board[0] : ((board[1] === (_ref9 = board[4]) && _ref9 === (_ref8 = board[7])) && _ref8 !== '') ? board[1] : ((board[2] === (_ref11 = board[5]) && _ref11 === (_ref10 = board[8])) && _ref10 !== '') ? board[2] : ((board[0] === (_ref13 = board[4]) && _ref13 === (_ref12 = board[8])) && _ref12 !== '') ? board[0] : ((board[2] === (_ref15 = board[4]) && _ref15 === (_ref14 = board[6])) && _ref14 !== '') ? board[2] : '';
      if (win !== '') {
        alert(win + ' won!');
        return resetBoard();
      }
    };
    $('#start-game').on('click', function(e) {
      clearBoard();
      $(this).hide();
      return $('#gameboard').fadeIn(500);
    });
    return $('.board-cell').on('click', function(e) {
      var mark;
      mark = isX ? 'x' : 'o';
      if (($(this).text().replace(/^\s+|\s+$/g, "")) === '') {
        $(this).text(mark);
        $(this).addClass(mark);
        isX = !isX;
      }
      return checkForWin();
    });
  });

}).call(this);

//# sourceMappingURL=game.map
